### ISSUE TITLE
add hide desktop/startmenu shortcuts to install-wayknow

### ISSUE THREAD

**Issue by si458** [Devolutions/WaykNow-ps#28]
Hi,

it would be nice if the was extra parameters to the Install-WaykNow script
to allow us to hide the desktop or start menu icons

its already possible to do this with the MSI setup
`msiexec /i WaykNow-x64-2020.2.2.0.msi INSTALLDESKTOPSHORTCUT="" INSTALLSTARTMENUSHORTCUT="" /passive`
this hides both desktop and start menu shortcuts

currently I just rename the desktop and shortcut icons after the msi has been installed,
but im unsure if the new autoupdate feature would then install the shortcut icons back?

Regards

Simon

**Comment by thenextman** [comment]
I've added the switches `-NoDesktopShortcut' and '-NoStartMenuShortcut' to opt out of those when using `Install-WaykNow`. The version on PSGallery will be updated shortly.

Thanks for the feedback!

**Comment by si458** [comment]
Hi

Brilliant thanks for this!?

But you didn’t answer my second question?

Will the new autoupdate feature install the desktop/start menu icons again or does it just replace the exe and update the control panel version?

Regards

Simon

**Comment by thenextman** [comment]
Hi Simon, sorry I missed that. I'll reply in the [forum thread](https://forum.devolutions.net/topics/33860/annoying-reload-required-for-new-branding).
